name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Run make test
      run: |
        make test

    - name: Run make all
      run: |
        make all

    - name: Generate orders.txt using Perl script
      run: |
        perl orderGenerator.pl > "orders.txt"
        
    - name: Archive the build artifacts
      run: |
        mkdir -p artifacts
        cp ./UtilityTester ./QuickTradeProcessor ./orders.txt artifacts/

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
