name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger the workflow only for tags starting with 'v'

jobs:
  release:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Run make test
      run: |
        make test

    - name: Run make all
      run: |
        make all

    - name: Generate orders.txt using Perl script
      run: |
        mkdir -p "input_file"
        perl orderGenerator.pl > "input_file/orders.txt"
        
    - name: Archive the build artifacts
      run: |
        mkdir -p artifacts
        cp ./UtilityTester ./QuickTradeProcessor artifacts/  # Include the executables you want to release

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/*
          "input_file/orders.txt"  # Include the orders.txt in the release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
